#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu May 14 22:49:29 2020

@author: usuario
"""
from numpy import random,linspace
from matplotlib import pyplot as pt







print("Pregunta 2:")
n=1000
print("Utilizando el método de Montecarlo, se generan",n,"experiemtos aleatorios para luego graficar la distribucion exponencial, con λ=1/500, en el histograma")
d=random.exponential(4,n)
nb=12
pt.hist(d,bins=linspace(-0.5,nb-0.5,nb+1),rwidth=0.95)
pt.hist(d,bins=nb)

#Que significa cada eje??